export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  MERGE_LOCKED: "MERGE_LOCKED",
  VOID_NOT_ALLOWED: "VOID_NOT_ALLOWED",
  NETWORK_UNAVAILABLE: "NETWORK_UNAVAILABLE"
} as const;
