export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  REPORT_ALREADY_VOID: "REPORT_ALREADY_VOID",
  MERGE_LOCKED_DISPATCHED: "MERGE_LOCKED_DISPATCHED",
  VOID_LOCKED_DISPATCHED: "VOID_LOCKED_DISPATCHED"
} as const;
